### ISSUE TITLE
OSX: zsh: command not found: navi

### ISSUE THREAD

**Issue by aredspacer** [denisidoro/navi#121]
When following the oh-my-zsh instructions I run into an issue where the command is not found. `zsh: command not found: navi` This prevents me from being able to use it as a widget. Are the instructions missing a step, am I supposed to link the executable in /usr/bin/local or something so that its available? If I install it using homebrew the command is available and will execute but the instructions are not clear on whether or not I have to follow two of the three possible steps to get it working properly.

**Comment by aredspacer** [comment]
It appears the missing step was to run make after cloning into the .oh-my-zsh/custom/plugins/navi folder.
```
plugins_dir="$ZSH_CUSTOM/plugins"
mkdir -p "$plugins_dir"
cd "$plugins_dir"
git clone https://github.com/denisidoro/navi
cd navi
make install
```

**Comment by denisidoro** [comment]
Running `make` works but the idea behind this process is not to (forcefully) have a globally accessible command.

@alxbl could you give a hand here? I'm not familiar with oh-my-zsh

**Comment by alxbl** [comment]
@aredspacer How are you trying to call `navi`? If you try to call it by running `navi` directly in the shell, it will not be found because it is not in your PATH. This is normal with the Oh-my-Zsh configuration steps, because it is indeed not being installed.

Adding it to your `plugins` array should let you call navi by hitting `Alt+G` from your terminal. If you want to have `navi` as an oh-my-zsh plugin for `Alt+G` and **also** want to also be able to call it from the command line directly, then you need to either:
- Install it to /usr/bin/local (via `sudo make install`)
- Set your `PATH` so that `navi` can be found.

Assuming you followed the install instructions, you can update your path like this:

```sh
export PATH=$PATH:"$ZSH_CUSTOM/plugins/navi"
```

And verify that it works by running `which navi`. You can add that export line to your `.zshrc`.

I guess the oh-my-zsh instructions should be clarified to avoid confusion. Let me know if this helped.

Cheers,
Alex

**Comment by aredspacer** [comment]
Yes this helps, I would agree that some updates could be made to clarify. Thanks for the response this issue can be closed.

**Comment by denisidoro** [comment]
@alxbl, if you want it, feel free to make any changes to the README. Otherwise, I'll basically copy+paste your instructions a few days from now.
