### ISSUE TITLE
fail replacement using sed regex references group

### ISSUE THREAD

**Issue by syedelec** [denisidoro/navi#131]
Hi,

Thanks for the project.

I have noticed a bug when I use the binding ctrl+g in bash. 
This command in a cheat fails because it replaces the `\1` by `^A`

In my cheat it's 
```
# Find primary, local IP address
ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/\1/p'
```

The command parsed after the binding is 
`ip -o route get to 8.8.8.8 | sed -n 's/.*src \([0-9.]\+\).*/^A/p'`

Terminal: tilix
bash 5.0.11

Thanks !

**Comment by denisidoro** [comment]
Does this only happen when you invoke navi via the keybinding? What if you invoke it via navi<enter>?

**Comment by syedelec** [comment]
I verified and it's also happening via command line `navi`

**Comment by syedelec** [comment]
I just updated to the latest version 0.14.2 and the issue is still present, am I missing something ?

**Comment by denisidoro** [comment]
😭 
I'll link into it more thoroughly next Monday, ok?

**Comment by syedelec** [comment]
No problem, take your time ;)

**Comment by denisidoro** [comment]
I'm still not able to find the root cause. This will take a few days more

**Comment by denisidoro** [comment]
For future reference:

---

Hi! This project suffers from a lot of string escaping issues, because it is implemented in bash. I believe I won't try to fix this at the moment.

I'll accept PR with fixes, though.

However, I plan to rewrite navi in rust in the near future (cf #154) and this bug won't happen anymore.

I'm sorry for the inconvenience and I hope you'll give the new version a try when it releases!

**Comment by denisidoro** [comment]
The version at master doesn't have this bug
