### ISSUE TITLE
Hide snippets for unavailable commands

### ISSUE THREAD

**Issue by denisidoro** [denisidoro/navi#140]
If yum isn't installed, for example, all snippets that start with yum should be hidden

1) this shouldn't impact startup time
2) if --show-all is used, there should be no filtering

**Comment by enisozgen** [comment]
This is really good idea to achieve since project is grooving well. 

I guess more easy to implement, you can define some kind of `NAVI_IGNORE` variable and users can add their groups there.
 
`NAVI_IGNORE='yum, mac, k8, kubernetes, etc, etc'`

In This case it will more more static than yours but still useful

Best Regards

**Comment by denisidoro** [comment]
A friend of mine suggested to, instead of checking the availability of a command given its snippet,  introduce a new syntax, as:

```
% version control
& git

# Change branch
git checkout <branch>
```

`& git` would determine that this cheat will only appear if `git` is installed, for example

**Comment by spoki0** [comment]
Unless I'm wrong, `which git` can be used to verify that the tool is installed on Linux as well.

**Comment by OriR** [comment]
@denisidoro 
If your leaning towards the new syntax, then it  should be applicable for tag section, command and variables.

let's say you have
```
% git

# print current commit
git show HEAD

# copy current commit
git show HEAD | pbcopy
```

If you were to add this new syntax only on the tag level you'd hide both commands because it'll probably be something like `& git, pbcopy`

If you were to add it only on the lowest level (commands & variables) it would be a huge copy/paste problem, for instance, in the example each command would need git.

I think adding them to all levels and then "merging" them would be the best in terms of UX.
If all the requirements in the tag section pass, you can look at the requirements in the command/variable and if all of them pass, you can show the snippet.

**Comment by denisidoro** [comment]
Could you please review https://github.com/denisidoro/navi/pull/258 as a possible workaround?

**Comment by denisidoro** [comment]
I'm closing this because there are workarounds for the purpose of hiding unwanted snippets
