### ISSUE TITLE
It eats string command until first semicolon.

### ISSUE THREAD

**Issue by bitozoid** [denisidoro/navi#182]
**Describe the bug**
When fetching a command, it eats everything until the first semicolon.

**To Reproduce**
```
$ ./navi --path cheats --print
```
Select 'ssh agent'.
You get `ssh-add`.

**Expected behavior**
As written in the git cheatsheet:
```
eval "$(ssh-agent -s)"; ssh-add
```

**Versions:**
 - OS: Exherbo Linux
 - zsh 5.7.1 (x86_64-pc-linux-gnu)
- navi 0.18.2

**Comment by denisidoro** [comment]
Hi! This project suffers from a lot of string escaping issues, because it is implemented in bash. I believe I won't try to fix this at the moment. 

I'll accept PR with fixes, though.

However, I plan to rewrite navi in rust in the near future (cf #154) and this bug won't happen anymore.

I'm sorry for the inconvenience and I hope you'll give the new version a try when it releases!
