### ISSUE TITLE
Keep cheats in a separate repository

### ISSUE THREAD

**Issue by ngirard** [denisidoro/navi#237]
How about keeping the cheats in their own repository and separating them from Navi ?

**Comment by denisidoro** [comment]
Thanks for the suggestion! 

Just to understand it better: what cons and pros you see if we split the repos?

**Comment by OriR** [comment]
I see it something like Homebrew taps.

There would either be a convention of repository names (`navicheats-mycheats`) or simply a git repo url that navi can understand.

You would use that git repo to download all of the cheats in there, then "import" them to be used within navi (internally, it can still have custom cheats paths, but it would be dynamic according to the place these cheats repos were to be downloaded).
It would allow you to reuse cheats written by others without contributing them to to main navi repo.

Right now it's hard to share cheats and so it's only useful for the more popular tools because they're in the main repo, or you'd have to write your own cheats for the more niche stuff you use.

**Comment by denisidoro** [comment]
Very nice idea! 

Some things that come to my mind:
1. `navi repo add user/repo` could install cheats to `~/.config/navi/cheats/user/repo` for example.
1. We could have a list of repositories as well for the user to choose from.
navi could get the list from a URL such as https://raw.githubusercontent.com/denisidoro/navi/master/list.txt for example.
1. `navi repo add user/repo/sub/folder` could be supported as well.
1. the default cheatsheets could simply be another repository that navi downloads from in the first run.

WDYT?

**Comment by denisidoro** [comment]
Related: https://github.com/denisidoro/navi/pull/238

**Comment by OriR** [comment]
1. Looks good 👍 The only thing is that I wouldn't want to limit it only to GitHub, that's why I suggested a full git repo url.
2. It would be nice as long as it's not limiting to only these repos, the point is to make it decentralized, right? 😉 
3. That's pretty great! that way you can store your cheats along with your dotfiles and people can still these cheats. My only issue here is that, as a maintainer, it's not super obvious that the path to the cheats needs to be constant, otherwise it might break navi.
4. That would be a great next step, it would be better if it could be downloaded during install time.

Another thing I would like to add is the ability to update cheats, something like `navi repo update` to pull all the latest changes for all cheats or `navi repo update user/repo` to update just the one.

Also, listing & removing remote repo cheats might be useful but I don't think it's mandatory in the first phase.

**Comment by ngirard** [comment]
In addition to what has been said, separate repos would also mean separate, cleaner commit histories, that would be easier to follow and help contributors.

**Comment by itmecho** [comment]
> the default cheatsheets could simply be another repository that navi downloads from in the first run.

I wouldn't even do that as there are a lot of default cheats that not everyone would use. If you're 3rd point works then you could convert the default cheats in their own repository into a folder structure so that people could run something like `navi repo add denisidoro/navi-community-cheats/openssl` for example.

Either that or if you wanted the default cheats as a special case, you could handle something like `navi repo add default`?

**Comment by itmecho** [comment]
You could even look into if it's worth creating a github org like `navi-rs` (`navi` is taken :disappointed: )
Then it would look something like

    navi repo add navi-rs/community-cheats

**Comment by OriR** [comment]
@itmecho 
If the purpose of what you're asking for is to reduce clutter then, assuming #140 would get solved, this doesn't really matter as you won't see the things you _can't_ use.
You don't have `cf` installed? you won't even see them in the menu.
You use `nodenv` instead of `nvm`? you would see just the `nodenv` cheats.

It would only matter if you're worried about saving space but then again, cheats are relatively small text files, downloading all of the cheats everyone created would probably be less than 5MB and if you can't space 5MB you probably have other issues 🤷‍♂

**Comment by OriR** [comment]
Also, think about it this way - at first you don't use a certain tool called `x`, then at some point in time you install `x`, how awesome would that be to start seeing cheats for it without actually ever doing anything? 

Obviously this won't apply to all tools, but as tools gain more popularity, their cheats can later be added to the main curated repo so that everyone can benefit.

**Comment by denisidoro** [comment]
@OriR, nice input but I'm not very confident #140 for performance issues. For things to be automagic, every navi run would need to perform dozens and dozens of `which somecmd` + apply filters when generating lists. I haven't benchmarked it yet but I bet it will be noticeable

**Comment by OriR** [comment]
@denisidoro 
You're right, but I think the performance issue can be solved.
Since `fzf` reads from stdin, you can stream the cheats as you filter them.
This means that you can run the `which somecmd` commands in the background and when a cheat passes this test you'll stream it to `fzf`.

But this discussion is unrelated to this issue and is better suited for #140 😃

**Comment by itmecho** [comment]
Hmm yea, those are good points. I still feel that not bundling any cheats with `navi` would be the cleanest way as you also don't need the special handling for finding the bundled files mentioned in #238. Everything could then just work with the location given by `dirs::config_dir()` instead of having to have a separate folder for the bundled cheats.

If `navi` gets the command to install cheats from a repo then all the cheats can be installed in that config directory on any system, removing the special case handling. I think a lot of the methods in `src/filesystem.rs` could be removed if this approach was taken as you would no longer care about the location of the binary, just the location of the cheats directory.

I'm not saying this is the way to do it, it's just how I would do it =]

**Comment by denisidoro** [comment]
The PR above could be a solution to downloading cheats during the first run.

**Comment by ngirard** [comment]
I think the welcome cheatsheet is a great idea !

**Comment by denisidoro** [comment]
Could you please review https://github.com/denisidoro/navi/pull/258?
