### ISSUE TITLE
Snippet with fzf fails with "Failed to read /dev/tty"

### ISSUE THREAD

**Issue by denisidoro** [denisidoro/navi#267]
The following cheatsheet fails:
```
% fzf

# call fzf
fzf
```

I have already tried all tricks with `exec`, `stty`, `< /dev/tty` and so on. Help needed.

**Comment by DenSA-Inc** [comment]
Your problem is the way linux handles tty's. Terminals are created by calls to [openpty](https://docs.rs/nix/0.17.0/nix/pty/fn.openpty.html) which creates something of a pipe that goes through the kernel terminal driver. The driver is responsible for turning ctrl-c into a SIGINT etc. Programs detect the presense of a terminal with [isatty](https://docs.rs/nix/0.17.0/nix/unistd/fn.isatty.html) which does some ioctl-calls and queries information associated with the file descriptor of stdin.

My guess is that running a command with `spawn()` (don't you need to call `wait()` on the child process?) does not "carry over" the terminal information of stdin. One solution is calling [exec](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html#tymethod.exec) on unix systems, but this replaces the process's image with the command you're calling and you can't do this more than once. Another solution would be creating your own terminal with openpty and proxying information through them, but this would be too much work for something that could hide bugs.

I'll see if I can find something about rusts `Command` and terminals

**Comment by DenSA-Inc** [comment]
As a side note: `exec` is performed in the bash process you create in navi, therefore it can't take over navi. And `< /dev/tty` only works if the bash process is already connected to a terminal.

**Comment by DenSA-Inc** [comment]
I found the issue: rather than some complicated terminal magic not working as intended you missed a call to [`Child::wait()`](https://doc.rust-lang.org/std/process/struct.Child.html#method.wait). I assume this way the `Child` struct gets dropped while the child process is still running. I'm not exactly sure what's supposed to happen then but adding the call to wait() fixed it. Maybe navi exited and closed the streams before fzf could read them.

I also performed a little test with a demo program that executed fzf without waiting for the child process. For some reason I got the fzf ui while my keypresses where sent to my shell and fzf seemingly at random. Sometimes I was able to narrow down fzf search results and sometimes I got autocompletion from my shell in the fzf ui.
