### ISSUE TITLE
CI and Release Process

### ISSUE THREAD

**Issue by mrVanDalo** [denisidoro/navi#278]
I add this ticket to talk a bit about the release process before I create a pull request ( I assume from #274 comments that is actually wanted, if not, just close this issue )

* github or/and travis?. Both seem good. I guess the can do both the same. (build stuff only on pull requests and other stuff on releases and other stuff on pushes, ... )
* I would reduce the scripting, like I call cargo right away in the `.travis.yml` I would also do the same in the github workflows. (what do you think?)

Do you have some points to add? The current releases seem to work fine (btw).

**Comment by denisidoro** [comment]
- if I were to choose one, I would keep GitHub Actions: everything remains self-contained, there's no 3rd party, releases are trivial to implement and so on.

- I didn't write code in the `.yml` file because I wanted to reuse everything done here: https://github.com/denisidoro/navi#using-install-script. I'm not discarding the possibility of writing code in `.yml`s, though.

**Comment by mrVanDalo** [comment]
makes sense, than I guess the only thing to do is, migrate the `test builds` for all the different architectures to the github actions, and delete the .travis.yml stuff, right?

**Comment by denisidoro** [comment]
If Travis is free, I would keep both: Github Actions for "happy path", quick scenarios and Travis for the hardwork testing against multiple targets.

**Comment by mrVanDalo** [comment]
Yeah it is free, for open source project, so for navi it is free. Alright, than I don't see anything to do, right?
