### ISSUE TITLE
Unsure how to specify the delimiter for selected parts of a --multi value

### ISSUE THREAD

**Issue by ngirard** [denisidoro/navi#342]
Consider the following, hopefully self-descripting snippet:
```
% pdf

# Concatenate pdf files

pdftk <files> cat output <pdf_output>

$ files: fd --type f -e pdf --- --multi
```

Using this snippet produces e.g.
```sh
pdftk a.pdf; b.pdf; c.pdf cat output out.pdf
```

while the correct command would be
```sh
pdftk a.pdf  b.pdf  c.pdf cat output out.pdf
```

Reading the README didn't provide guidance about how to use " " as delimiter for the selected parts instead of the semicolumn.

Also, in this particular case, it would be useful to be able to forward the `--tac` option to `fzf` in order to be able to choose the files from a list sorted from a to z instead of the opposite. I'm willing to open a new issue for this if you wish.

**Comment by denisidoro** [comment]
Could you please try this?
```bash
% pdf

# Concatenate pdf files
files=($(echo "<files>"))
echo pdftk "${files[@]:-}" cat output <pdf_output>

$ files: fd --type f -e pdf --- --multi --overrides '--tac'
```

**Comment by ngirard** [comment]
@denisidoro, thanks for your feedback.

I'm embarrassed to say it, but I'm having a problem with the proposed solution.

One very interesting benefit of Navi cheats is to lower the bar for grasping the command-line and allow to gradually learn useful commands at everyone's pace. As a matter of fact I don't need a cheat to use pdftk myself, but 2 of my relatives would benefit from it.

In other words, a cheat written like
```
pdftk <files> cat output <pdf_output>
```
has a great educational value.

It seems to me, like this value is lost when the cheat is written like
```
files=($(echo "<files>"))
pdftk "${files[@]:-}" cat output <pdf_output>
```

What do you think ?

Also I'm glad there's a way of forwarding the `--tac` option. How about adding `--overrides` to the README ?

Cheers

**Comment by denisidoro** [comment]
I totally see your point!

However, I'm afraid it isn't possible to change the code so that `pdftk <files> cat output <pdf_output>` will work as you expected because the other use case would break (the case where the user really wants to have 1 argument with multiline division).

Previous versions of navi tried to do that and there was always a corner case. For example, it used to add quotes to multi-word values. However, it broke the use case of people who wanted to inject text inside a string such as in:
`osascript -e "some random code <other_code> foo bar"`

I've discovered that the most flexible behavior is to make navi as dumb as possible.

That being said, we can think of some DSLs to support this use case. Such as `pdtfk <files:spread>` or `$ files: echo foo bar --- --spread` or something like that.

I'm open for suggestions! Even more for PRs 😅 
Just keep this is mind: https://github.com/denisidoro/navi/issues/325#issuecomment-606103882

WDYT? And thanks for the raising this point!

**Comment by denisidoro** [comment]
Regarding `--overrides`, actually I want to remove that and fix https://github.com/denisidoro/navi/issues/317 so I didn't document it to prevent the breaking change.

**Comment by denisidoro** [comment]
Closing as there's a workaround already. Feel free to reopen it if you think it makes sense! 👍

**Comment by ngirard** [comment]
Hi @denisidoro,
which workaround are we talking about here ?
