### ISSUE TITLE
Nested variables UX

### ISSUE THREAD

**Issue by hnrklssn** [denisidoro/navi#444]
**Describe the bug**
When nesting a free text variable inside another, the prompt for filling out the free text variable does not include the name of the free text variable.

**To Reproduce**
1. Include the following cheatsheet:
```
% toplevel
@ sub1
@ sub2
# echo vars
echo <sub1_var>

% sub1
$ sub1_var: echo "sub1_var_text + <sub2_var>

% sub2
$ sub2_var: echo "sub2_var_text + <free_text_var>"
```

2. Run the toplevel command in navi

**Expected behavior**
For navi to tell me that I'm filling out `free_text_var`, ideally that it's part of evaluating `sub2_var` inside `sub1_var`.

**Screenshots**
![Screenshot from 2020-12-08 15-47-59](https://user-images.githubusercontent.com/14333906/101498890-e7044500-396c-11eb-81f3-90250bdb9afe.png)

**Versions:**
 - OS: Ubuntu 18.04
 - Shell Version: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)

**Additional context**
I have variables that need to be free text in some contexts and can have a list of alternatives in others, so I need to have these indirect dependencies between them to avoid duplicating them in every cheatsheet.

**Comment by denisidoro** [comment]
This seems a hard problem to solve because it will require some refactors 😢 

The variable window is a quick solution I came up with that covers 95% of the cases but is completely broken for complex cases (such as the ones that use `--map`, `--nth`, etc)

Anyway, thanks for reporting! I'll try to look into it.

**Comment by denisidoro** [comment]
But it's worth mentioning the following.

If you have a cheat like this...
```

# my example
echo "<example>"

$ example: echo 'foo;bar' | tr ';' '\n'
```

Then if you select the snippet you have a few options:
- if you want to use `lorem` as value, you can simply type `lorem` and hit `<enter>` -- because there's no suggestion that contains `lorem`
- if you want to use `f` as value, you can simply type `f` and hit `<tab>` -- hitting `<enter>` wouldn't work because it would select `foo`

Does that cover you use case for the time being?

**Comment by hnrklssn** [comment]
That helps a bit! But of course it would be even nicer to be able to keep the variables modular. Worst case it can be worked around with code duplication as well.
