### ISSUE TITLE
Open Command into an Editor

### ISSUE THREAD

**Issue by 1995parham** [denisidoro/navi#448]
Provide a way that user can edit command into its $EDITOR and replace variables instead of using the navi itself.

**Comment by denisidoro** [comment]
Thanks for the suggestion!

But could you elaborate, please?

navi's strongest advantage is the ability to suggest variables so that you simply choose one of the suggestions.

If you only want to have a list of snippets and edit a selection in vim, for example, then I would do something like:
- use the [shell widget](https://github.com/denisidoro/navi/blob/master/docs/installation.md#installing-the-shell-widget)
- [edit the command](https://unix.stackexchange.com/questions/6620/how-to-edit-command-line-in-full-screen-editor-in-zsh) before running it

Does that answer your question or did I miss something?

**Comment by 1995parham** [comment]
Thanks for your complete answers. Currently I am using the _edit the command before running it__ but I want some kind of cheat sheet for my commands. I will check your solution with `fzf+vim+eval`.
