### ISSUE TITLE
Directly execute command after fzf choice without hitting Return key

### ISSUE THREAD

**Issue by ejemba** [denisidoro/navi#545]
**Is your feature request related to a problem? Please describe.**
Not really a problem. More a convenience in some case.
I would like after Ctrl-g, after the line fully filled or not that the command execute directly without having to hit return

**Describe the solution you'd like**
Perhaps a keywords or char in the .cheat before the command to indicate that we want this particular command executes directly
```
; here I use (~) to indicate the behaviour
# list files using Thor hammer (~)
ls -thor 
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by denisidoro** [comment]
Instead of using the shell widget you call the navi bin directly (type `navi` and hit enter).

Another solution is to customize the widget to your needs: see the contents of `navi widget bash` for example and adapt it accordingly. Say the result from `navi --print` is `$res`. Instead of appending `$res` to the prompt line, you'll want to `eval "$res"`.

This way you can even have different keybindings for different needs.

**Comment by ejemba** [comment]
@denisidoro thank you I think I can achieve it this way.
I'm using zsh will modify the widget accordingly. 

A last question, how could I handle the fact that I want this behaviour according a marker in the command. How can I get the information inside the widget ?

**Comment by wiegell** [comment]
@ejemba  do you mind sharing your modified script? Kind regards
