### ISSUE TITLE
shell widget not closing on ESC

### ISSUE THREAD

**Issue by gennaro-tedesco** [denisidoro/navi#546]
**Describe the bug**
The shell widget needs to be `<ESC>`aped twice to close down.

Is this the expected behaviour or how is the widget intended to be closed?

**To Reproduce**
1. Invoke the shell widget with `Ctrl+g`
2. close it via `<ESC>`

**Expected behavior**
One `<ESC>` is sufficient to close the widget.

**Screenshots**

https://user-images.githubusercontent.com/15387611/117171627-528ef900-adcb-11eb-96e6-970bf703776a.mov

**Versions:**
 - OS: macOS BigSur 11.3.1
 - Shell Version: zsh 5.8 (x86_64-apple-darwin20.0)

**Additional context**
I suppose this has more to do with the shell itself than the program, however I would like to ask if other users (or yourself) have seen this before and how to address it.

**Comment by dgengtek** [comment]
Was wondering the same with bash.

https://github.com/denisidoro/navi/blob/master/shell/navi.plugin.zsh

Either remove the if conditional from `_navi_call()` or replace every invocation of `_navi_call` with just `navi` in `_navi_widget()`.

I am not sure though why _navi_call() is required though. Only found related issues where something has been fixed because of #367 and #213. Maybe this is legacy for some terminals before input parsing has been rewritten to rust?

**Comment by denisidoro** [comment]
The navi widget is designed to support a fallback selection.

Say you've typed `foo bar | lorem` and hit `Ctrl-G`. Then navi will show results `lorem`-related. However, if there's no match for `lorem`, navi will automatically close. navi is then launched again but showing all results, which is what you would probably expect.

The consequence is that you have to press `ESC` twice in the "happy paths." I understand this is confusing in these cases.

I'll revisit the shell widget implementation and address this in the next release, most likely.

**Comment by gennaro-tedesco** [comment]
Thank you for the explanation, it makes sense. Perhaps I am trivialising it (my understanding may be off) but would that not require just to check whether the invocation of `navi` comes from a non-null piped string (former case) or null input (latter case, "happy path" with mere shell invocation)?
