### ISSUE TITLE
Nothing of cheats available on Windows

### ISSUE THREAD

**Issue by acodecow** [denisidoro/navi#576]
**Describe the bug**
navi doesn't not recognize any cheat sheets.

**To Reproduce**
run navi, if *current working directory* is not at `C:/` driver,

**Expected behavior**
It should **NOT REWRITE** disk driver character when query profile data

**Screenshots**

![image](https://user-images.githubusercontent.com/13063376/124584523-edb55500-de86-11eb-987d-e17c2bda7f81.png)

**Versions:**
 - OS: Windows
 - using any windows shell: navi 2.16.0

**Additional context**
sceenshot from `procmon` capture.

**Comment by denisidoro** [comment]
Thanks for troubleshooting, but I'm afraid I didn't get it.

Do you mean that `navi.exe` should `CreateFile` in `C:\Users\...\cheats` but instead it's trying to create it in `D:\Users\...\cheats` which is invalid?

**Comment by LittleboyHarry** [comment]
![image](https://user-images.githubusercontent.com/13063376/124614218-9aeb9580-dea6-11eb-8b3d-b295d1cc7578.png)

**Comment by denisidoro** [comment]
I believe this is a bug in https://docs.rs/directories-next/2.0.0/directories_next/struct.ProjectDirs.html#method.config_dir

I'll need to investigate this upstream

**Comment by scillidan** [comment]
I also had the similar problem.
I run it in `Cmder`.
![image](https://user-images.githubusercontent.com/19889610/185138892-5efaf3d4-1fd2-4d7c-8424-9048267b038a.png)

**Comment by phanirithvij** [comment]
@scillidan I think you need to set cmd.exe as the shell in navi config. ref: https://github.com/denisidoro/navi/issues/40#issuecomment-845495970

**Comment by zjp-CN** [comment]
This is caused by using `:` in path join https://github.com/denisidoro/navi/blob/6f316ec7eb2f1f56a7609048e67860eb84c1aacf/src/config/mod.rs#L72

https://github.com/denisidoro/navi/blob/6f316ec7eb2f1f56a7609048e67860eb84c1aacf/src/filesystem.rs#L155

https://github.com/denisidoro/navi/blob/6f316ec7eb2f1f56a7609048e67860eb84c1aacf/src/filesystem.rs#L25-L27

It's incorrect since `:` is a valid component on Windows. It'd be better to use PathBuf instead of String for path and carry the vec of path along.

Plus, I think we should introduce logging, otherwise it's hard to know where goes wrong. I made a small commit here https://github.com/zjp-CN/navi/commit/d1699dfaf1eadcc4a650de979764a6815c1f44d2

**Comment by zjp-CN** [comment]
> It's incorrect since : is a valid component on Windows. It'd be better to use PathBuf instead of String for path and carry the vec of path along.

Another workaround is to make the separator platform-specific. The PR is [here](https://github.com/denisidoro/navi/pull/840).

![image](https://github.com/denisidoro/navi/assets/25300418/9107cde4-ca20-4afe-9fbb-0bb0c3db2041)

**Comment by scillidan** [comment]
@zjp-CN Thanks! I will try it later.
