### ISSUE TITLE
Unable to use NAVI with TMUX in SSH session

### ISSUE THREAD

**Issue by darthsiderius** [denisidoro/navi#816]
**Describe the bug**
Unable to use NAVI with TMUX in SSH session

**To Reproduce**

1. Install Navi
2. Install TMUX 
3. Update TMUX config to include the navi widget - shown here https://github.com/denisidoro/navi/blob/master/docs/tmux.md
4. SSH into a server
5. Use navi hot key
6. observe nothing opens

**Expected behavior**
Navi opens

**Versions:**

- OS: linux ubuntu
- Bash Version GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

**Additional context**
Sshing into a ubuntu ec2 box, expecting to use navi during this session when its integrated with TMUX.

**Comment by AntonovskyIV** [comment]
Has anyone managed to fix this bug? I found out that the reason is that the command is executed in the ssh shell, and the values ​​of the variables are taken from the host, i.e. when I execute the systemctl status <service>, the services ($ service: systemctl list-units ...) are taken from the host, not from the ssh shell.
