### ISSUE TITLE
Issue with quoting

### ISSUE THREAD

**Issue by calexicoz** [denisidoro/navi#99]
Hi @denisidoro,

It seems that right now, parameters are always enclosed in quotes. While this works in most cases, it makes it hard to do simple commands like:

```bash
curl http://example.com/<arg1>/foo/<arg2>
```

The resulting command would be:

```bash
curl http://example.com/"value1"/foo/"value2"
```

Instead of simply:

```bash
curl http://example.com/value1/foo/value2
```

Ideas?

Thanks.

**Comment by denisidoro** [comment]
This isn't a problem per se because bash will interpret this correctly despite the additional quotes.

To properly fix this, the code should know when an argument is "glued" to other words, but I guess I need regexes with lookahead for that, and portability would be very difficult. 

In the meantime, I can quote if, and only if, the value has more than one word. That should cover most of the cases.

**Comment by calexicoz** [comment]
Another option could be to allow the user to decide, with maybe something like `<r foo>` or `<<foo>>` for "raw output" so to speak. Though it's true that the "one word" rule will likely cover the vast majority of cases.
